// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(empleadoDbContext))]
    partial class empleadoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.asignacion", b =>
                {
                    b.Property<int>("asignacionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Bio");

                    b.Property<string>("Nombre");

                    b.HasKey("asignacionId");

                    b.ToTable("asignacion");
                });

            modelBuilder.Entity("Model.departamento", b =>
                {
                    b.Property<int>("departamentoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Bio");

                    b.Property<string>("Nombre");

                    b.HasKey("departamentoId");

                    b.ToTable("departamento");
                });

            modelBuilder.Entity("Model.empleado", b =>
                {
                    b.Property<int>("empleadoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Bio");

                    b.Property<string>("Nombre");

                    b.HasKey("empleadoId");

                    b.ToTable("empleado");
                });

            modelBuilder.Entity("Model.reclamacion", b =>
                {
                    b.Property<int>("reclamacionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Bio");

                    b.Property<string>("Nombre");

                    b.HasKey("reclamacionId");

                    b.ToTable("reclamacion");
                });
#pragma warning restore 612, 618
        }
    }
}
